export enum NotificationType {
   // Account
  ACCOUNT = "ACCOUNT",
  LOGIN = "LOGIN",
  REGISTER = "REGISTER",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  EMAIL_VERIFIED = "EMAIL_VERIFIED",

  // CV
  CV_UPLOADED = "CV_UPLOADED",
  CV_ANALYZED = "CV_ANALYZED",
  ATS_ANALYSIS_READY = "ATS_ANALYSIS_READY",

  // Interview
  INTERVIEW_CREATED = "INTERVIEW_CREATED",
  INTERVIEW_STARTED = "INTERVIEW_STARTED",
  INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED",

  // Report
  REPORT_READY = "REPORT_READY",

  // Reminder
  REMINDER = "REMINDER",

  // Subscription
  SUBSCRIPTION = "SUBSCRIPTION",

  // System
  SYSTEM = "SYSTEM",
  
  PAYMENT = "PAYMENT",
}